INSERT INTO repositories (id, path) VALUES (1, '/mnt/share/Telechargements');
INSERT INTO repositories (id, path) VALUES (2, '/mnt/share/Telechargements/tv');

-- INSERT INTO rules (regex, destination, repo) VALUES ('', '', 1);

-- US TV

--REPO1
INSERT INTO rules (regex, destination, repo) VALUES ('^.*pretty.*little.*liars.*$', '/mnt/share/Videos/TV/Pretty Little Liars', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*house.*of.*cards.*$', '/mnt/share/Videos/TV/House of Cards', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*the.*100.*$', '/mnt/share/Videos/TV/The 100', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*mr.*pickles.*$', '/mnt/share/Videos/TV/Mr. Pickles', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*modern.*family.*$', '/mnt/share/Videos/TV/Modern Family', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*revenge.*$', '/mnt/share/Videos/TV/Revenge', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*the.*vampire.*diaries.*$', '/mnt/share/Videos/TV/The Vampire Diaries', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*the.*simpsons.*$', '/mnt/share/Videos/TV/The Simpsons', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*south.*park.*$', '/mnt/share/Videos/TV/South Park', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*legends.*of.*tomorrow.*$', '/mnt/share/Videos/TV/DC''s Legends of Tomorrow', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*greys.*anatomy.*$', '/mnt/share/Videos/TV/Greys Anatomy', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*game.*of.*thrones.*$', '/mnt/share/Videos/TV/Game of Thrones', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*devious.*maids.*$', '/mnt/share/Videos/TV/Devious Maids', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*the.*shannara.*chronicles.*$', '/mnt/share/Videos/TV/The Shannara Chronicles', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*supergirl.*$', '/mnt/share/Videos/TV/Supergirl', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*suits.*$', '/mnt/share/Videos/TV/Suits', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*the.*big.*bang.*theory.*$', '/mnt/share/Videos/TV/The Big Bang Theory', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*arrow.*$', '/mnt/share/Videos/TV/Arrow', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*minority.*report.*$', '/mnt/share/Videos/TV/Minority Report', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*shameless.*$', '/mnt/share/Videos/TV/Shameless', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*defiance.*$', '/mnt/share/Videos/TV/Defiance', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*mom.*$', '/mnt/share/Videos/TV/Mom', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*scorpion.*$', '/mnt/share/Videos/TV/Scorpion', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*the.*originals.*$', '/mnt/share/Videos/TV/The Originals', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*the.*mentalist.*$', '/mnt/share/Videos/TV/The Mentalist', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*unreal.*$', '/mnt/share/Videos/TV/UnReal', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*gotham.*$', '/mnt/share/Videos/TV/Gotham', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*big.*order.*$', '/mnt/share/Videos/TV/Big Order', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*killjoys.*$', '/mnt/share/Videos/TV/Killjoys', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*the.*walking.*dead.*$', '/mnt/share/Videos/TV/The Walking Dead', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*extant.*$', '/mnt/share/Videos/TV/Extant', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*friends.*with.*better.*lives.*$', '/mnt/share/Videos/TV/Friends with Better Lives', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*awkward.*$', '/mnt/share/Videos/TV/Awkward', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*sons.*of.*anarchy.*$', '/mnt/share/Videos/TV/Sons of Anarchy', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*shameless.*us.*$', '/mnt/share/Videos/TV/Shameless (US)', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*mr.*robot.*$', '/mnt/share/Videos/TV/Mr Robot', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*under.*the.*dome.*$', '/mnt/share/Videos/TV/Under the Dome', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*vikings.*$', '/mnt/share/Videos/TV/Vikings', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*dark.*matter.*$', '/mnt/share/Videos/TV/Dark Matter', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*citizen.*khan.*$', '/mnt/share/Videos/TV/Citizen Khan', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*heroes.*reborn.*$', '/mnt/share/Videos/TV/Heroes Reborn', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*the.*flash.*$', '/mnt/share/Videos/TV/The Flash', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*better.*call.*saul.*$', '/mnt/share/Videos/TV/Better Call Saul', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*community.*$', '/mnt/share/Videos/TV/Community', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*limitless.*$', '/mnt/share/Videos/TV/Limitless', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*quantico.*$', '/mnt/share/Videos/TV/Quantico', 1);

--REPO2
INSERT INTO rules (regex, destination, repo) VALUES ('^.*pretty.*little.*liars.*$', '/mnt/share/Videos/TV/Pretty Little Liars', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*house.*of.*cards.*$', '/mnt/share/Videos/TV/House of Cards', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*the.*100.*$', '/mnt/share/Videos/TV/The 100', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*mr.*pickles.*$', '/mnt/share/Videos/TV/Mr. Pickles', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*modern.*family.*$', '/mnt/share/Videos/TV/Modern Family', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*revenge.*$', '/mnt/share/Videos/TV/Revenge', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*the.*vampire.*diaries.*$', '/mnt/share/Videos/TV/The Vampire Diaries', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*the.*simpsons.*$', '/mnt/share/Videos/TV/The Simpsons', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*south.*park.*$', '/mnt/share/Videos/TV/South Park', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*legends.*of.*tomorrow.*$', '/mnt/share/Videos/TV/DC''s Legends of Tomorrow', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*greys.*anatomy.*$', '/mnt/share/Videos/TV/Greys Anatomy', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*game.*of.*thrones.*$', '/mnt/share/Videos/TV/Game of Thrones', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*devious.*maids.*$', '/mnt/share/Videos/TV/Devious Maids', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*the.*shannara.*chronicles.*$', '/mnt/share/Videos/TV/The Shannara Chronicles', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*supergirl.*$', '/mnt/share/Videos/TV/Supergirl', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*suits.*$', '/mnt/share/Videos/TV/Suits', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*the.*big.*bang.*theory.*$', '/mnt/share/Videos/TV/The Big Bang Theory', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*arrow.*$', '/mnt/share/Videos/TV/Arrow', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*minority.*report.*$', '/mnt/share/Videos/TV/Minority Report', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*shameless.*$', '/mnt/share/Videos/TV/Shameless', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*defiance.*$', '/mnt/share/Videos/TV/Defiance', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*mom.*$', '/mnt/share/Videos/TV/Mom', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*scorpion.*$', '/mnt/share/Videos/TV/Scorpion', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*the.*originals.*$', '/mnt/share/Videos/TV/The Originals', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*the.*mentalist.*$', '/mnt/share/Videos/TV/The Mentalist', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*unreal.*$', '/mnt/share/Videos/TV/UnReal', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*gotham.*$', '/mnt/share/Videos/TV/Gotham', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*big.*order.*$', '/mnt/share/Videos/TV/Big Order', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*killjoys.*$', '/mnt/share/Videos/TV/Killjoys', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*the.*walking.*dead.*$', '/mnt/share/Videos/TV/The Walking Dead', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*extant.*$', '/mnt/share/Videos/TV/Extant', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*friends.*with.*better.*lives.*$', '/mnt/share/Videos/TV/Friends with Better Lives', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*awkward.*$', '/mnt/share/Videos/TV/Awkward', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*sons.*of.*anarchy.*$', '/mnt/share/Videos/TV/Sons of Anarchy', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*shameless.*us.*$', '/mnt/share/Videos/TV/Shameless (US)', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*mr.*robot.*$', '/mnt/share/Videos/TV/Mr Robot', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*under.*the.*dome.*$', '/mnt/share/Videos/TV/Under the Dome', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*vikings.*$', '/mnt/share/Videos/TV/Vikings', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*dark.*matter.*$', '/mnt/share/Videos/TV/Dark Matter', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*citizen.*khan.*$', '/mnt/share/Videos/TV/Citizen Khan', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*heroes.*reborn.*$', '/mnt/share/Videos/TV/Heroes Reborn', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*the.*flash.*$', '/mnt/share/Videos/TV/The Flash', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*better.*call.*saul.*$', '/mnt/share/Videos/TV/Better Call Saul', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*community.*$', '/mnt/share/Videos/TV/Community', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*limitless.*$', '/mnt/share/Videos/TV/Limitless', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*quantico.*$', '/mnt/share/Videos/TV/Quantico', 2);

-- JPN TV

-- REP01
INSERT INTO rules (regex, destination, repo) VALUES ('^.*world.*trigger.*$', '/mnt/share/Videos/ANIMES/World Trigger', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*aldnoah.*zero.*$', '/mnt/share/Videos/ANIMES/Aldnoah Zero', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*boku.*dake.*ga.*inai.*machi.*$', '/mnt/share/Videos/ANIMES/Boku dake ga Inai Machi', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*danmachi.*$', '/mnt/share/Videos/ANIMES/DanMachi', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*space.*brothers.*$', '/mnt/share/Videos/ANIMES/Space Brothers', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*nisekoi.*s2.*$', '/mnt/share/Videos/ANIMES/Nisekoi S2', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*arslan.*senki.*$', '/mnt/share/Videos/ANIMES/Arslan Senki', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*overlord.*$', '/mnt/share/Videos/ANIMES/Overlord', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*subete.*ga.*f.*ni.*naru.*$', '/mnt/share/Videos/ANIMES/Subete ga F ni Naru', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*akagami.*no.*shirayukihime.*$', '/mnt/share/Videos/ANIMES/Akagami no Shirayukihime', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*ore.*monogatari.*$', '/mnt/share/Videos/ANIMES/Ore Monogatari!!', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*hellsing.*ultimate.*$', '/mnt/share/Videos/ANIMES/Hellsing Ultimate', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*amaama.*to.*inazuma.*$', '/mnt/share/Videos/ANIMES/Amaama to Inazuma', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*rekan.*$', '/mnt/share/Videos/ANIMES/Re-Kan!', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*parasyte.*.*the.*maxim.*$', '/mnt/share/Videos/ANIMES/Parasyte - the maxim', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*etotama.*$', '/mnt/share/Videos/ANIMES/Etotama', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*psycho.*pass.*2.*$', '/mnt/share/Videos/ANIMES/Psycho Pass 2', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*mayoiga.*$', '/mnt/share/Videos/ANIMES/Mayoiga', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*one.*piece.*$', '/mnt/share/Videos/ANIMES/One Piece', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*btooom.*$', '/mnt/share/Videos/ANIMES/Btooom', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*mikagura.*gakuen.*kumikyoku.*$', '/mnt/share/Videos/ANIMES/Mikagura Gakuen Kumikyoku', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*musaigen.*no.*phantom.*world.*$', '/mnt/share/Videos/ANIMES/Musaigen no Phantom World', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*kekkai.*sensen.*$', '/mnt/share/Videos/ANIMES/Kekkai Sensen', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*luck.*logic.*$', '/mnt/share/Videos/ANIMES/Luck & Logic', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*shingeki.*no.*bahamut.*$', '/mnt/share/Videos/ANIMES/Shingeki no Bahamut', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*horriblesubs.*nagi.*no.*asakura.*$', '/mnt/share/Videos/ANIMES/Nagi no Asukara', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*akuma.*no.*riddle.*$', '/mnt/share/Videos/ANIMES/Akuma no Riddle', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*hai.*to.*gensou.*no.*gimgar.*$', '/mnt/share/Videos/ANIMES/Hai to Gensou no Grimgar', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*wolf.*rain.*$', '/mnt/share/Videos/ANIMES/Wolf''s Rain', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*bungou.*stray.*dogs.*$', '/mnt/share/Videos/ANIMES/Bungou Stray Dogs', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*mekakucity.*actors.*$', '/mnt/share/Videos/ANIMES/Mekakucity Actors', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*terra.*formars.*$', '/mnt/share/Videos/ANIMES/Terra Formars', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*uta.*no.*prince.*sama.*revolutions.*$', '/mnt/share/Videos/ANIMES/Uta no Prince Sama Revolutions', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*she.*and.*her.*cat.*everything.*flows.*$', '/mnt/share/Videos/ANIMES/She and Her Cat - Everything Flows', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*plastic.*memories.*$', '/mnt/share/Videos/ANIMES/Plastic Memories', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*garo.*.*the.*animation.*$', '/mnt/share/Videos/ANIMES/Garo - The Animation', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*trinity.*seven.*$', '/mnt/share/Videos/ANIMES/Trinity Seven', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*seraph.*of.*the.*end.*s2.*$', '/mnt/share/Videos/ANIMES/Seraph of the End S2', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*fairy.*tail.*s2.*$', '/mnt/share/Videos/ANIMES/Fairy Tail S2', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*knights.*of.*sidonia.*$', '/mnt/share/Videos/ANIMES/Knights of Sidonia', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*another.*$', '/mnt/share/Videos/ANIMES/Another', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*hibike.*euphonium.*$', '/mnt/share/Videos/ANIMES/Hibike! Euphonium', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*ao.*no.*kanata.*no.*four.*rhythm.*$', '/mnt/share/Videos/ANIMES/Ao no Kanata no Four Rhythm', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*rolling.*girls.*$', '/mnt/share/Videos/ANIMES/Rolling Girls', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*heavy.*object.*$', '/mnt/share/Videos/ANIMES/Heavy Object', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*shigatsu.*wa.*kimi.*no.*uso.*$', '/mnt/share/Videos/ANIMES/Shigatsu wa Kimi no Uso', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*blade.*and.*soul.*$', '/mnt/share/Videos/ANIMES/Blade and Soul', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*dagashi.*kashi.*$', '/mnt/share/Videos/ANIMES/Dagashi Kashi', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*brynhildr.*in.*the.*darkness.*$', '/mnt/share/Videos/ANIMES/Brynhildr in the Darkness', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*robotics.*notes.*$', '/mnt/share/Videos/ANIMES/Robotics;Notes', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*re.*life.*$', '/mnt/share/Videos/ANIMES/ReLIFE', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*death.*parade.*$', '/mnt/share/Videos/ANIMES/Death Parade', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*yahari.*ore.*no.*seishun.*love.*come.*wa.*machigatteiru.*zoku.*$', '/mnt/share/Videos/ANIMES/Yahari Ore no Seishun Love Come wa Machigatteiru Zoku', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*kuromukuro.*$', '/mnt/share/Videos/ANIMES/Kuromukuro', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*seraph.*of.*the.*end.*$', '/mnt/share/Videos/ANIMES/Seraph of the End', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*gintama.*s3.*$', '/mnt/share/Videos/ANIMES/Gintama S3', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*bokura.*wa.*minna.*kawaisou.*$', '/mnt/share/Videos/ANIMES/Bokura wa Minna Kawaisou', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*urawa.*no.*usagi.*chan.*$', '/mnt/share/Videos/ANIMES/Urawa no Usagi-chan', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*show.*by.*rock.*$', '/mnt/share/Videos/ANIMES/Show By Rock!!', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*taboo.*tatoo.*$', '/mnt/share/Videos/ANIMES/Taboo Tatoo', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*rokka.*no.*yuusha.*$', '/mnt/share/Videos/ANIMES/Rokka no Yuusha', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*tokyo.*ghoul.*$', '/mnt/share/Videos/ANIMES/Tokyo Ghoul', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*soul.*eater.*not.*$', '/mnt/share/Videos/ANIMES/Soul Eater Not!', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*zankyou.*no.*terror.*$', '/mnt/share/Videos/ANIMES/Zankyou no Terror', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*ghost.*in.*the.*shell.*arise.*.*alternative.*architecture.*$', '/mnt/share/Videos/ANIMES/Ghost in the Shell Arise - Alternative Architecture', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*concrete.*revolution.*$', '/mnt/share/Videos/ANIMES/Concrete Revolutio', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*dramatical.*murder.*$', '/mnt/share/Videos/ANIMES/DRAMAtical Murder', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*punch.*line.*$', '/mnt/share/Videos/ANIMES/Punch Line', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*god.*eater.*$', '/mnt/share/Videos/ANIMES/GOD EATER', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*barakamon.*$', '/mnt/share/Videos/ANIMES/Barakamon', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*danna.*ga.*nani.*wo.*itteiru.*ka.*wakaranai.*ken.*s2.*$', '/mnt/share/Videos/ANIMES/Danna ga Nani wo Itteiru ka Wakaranai Ken S2', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*ushio.*to.*tora.*$', '/mnt/share/Videos/ANIMES/Ushio to Tora', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*akame.*ga.*kill.*$', '/mnt/share/Videos/ANIMES/Akame Ga Kill!', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*akawa.*under.*the.*bridge.*$', '/mnt/share/Videos/ANIMES/Arakawa Under the Bridge', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*psycho.*pass.*extended.*edition.*$', '/mnt/share/Videos/ANIMES/PSYCHO-PASS Extended Edition', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*beelzebub.*$', '/mnt/share/Videos/ANIMES/Beelzebub', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*houkago.*no.*pleiades.*$', '/mnt/share/Videos/ANIMES/Houkago no Pleiades', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*tokyo.*esp.*$', '/mnt/share/Videos/ANIMES/Tokyo ESP', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*new.*game.*$', '/mnt/share/Videos/ANIMES/New Game!', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*saijaku.*muhai.*no.*bahamut.*$', '/mnt/share/Videos/ANIMES/Saijaku Muhai no Bahamut', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*black.*bullet.*$', '/mnt/share/Videos/ANIMES/Black Bullet', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*gangsta.*$', '/mnt/share/Videos/ANIMES/Gangsta', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*flying.*witch.*$', '/mnt/share/Videos/ANIMES/Flying Witch', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*re.*zero.*kara.*hajimeru.*isekai.*seikatsu.*$', '/mnt/share/Videos/ANIMES/Re Zero kara Hajimeru Isekai Seikatsu', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*hunter.*x.*hunter.*$', '/mnt/share/Videos/ANIMES/Hunter X Hunter', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*assassination.*classroom.*$', '/mnt/share/Videos/ANIMES/Assassination Classroom', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*kuma.*miko.*$', '/mnt/share/Videos/ANIMES/Kuma Miko', 1);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*planetarian.*$', '/mnt/share/Videos/ANIMES/Planetarian', 1);

-- REP02
INSERT INTO rules (regex, destination, repo) VALUES ('^.*world.*trigger.*$', '/mnt/share/Videos/ANIMES/World Trigger', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*aldnoah.*zero.*$', '/mnt/share/Videos/ANIMES/Aldnoah Zero', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*boku.*dake.*ga.*inai.*machi.*$', '/mnt/share/Videos/ANIMES/Boku dake ga Inai Machi', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*danmachi.*$', '/mnt/share/Videos/ANIMES/DanMachi', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*space.*brothers.*$', '/mnt/share/Videos/ANIMES/Space Brothers', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*nisekoi.*s2.*$', '/mnt/share/Videos/ANIMES/Nisekoi S2', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*arslan.*senki.*$', '/mnt/share/Videos/ANIMES/Arslan Senki', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*overlord.*$', '/mnt/share/Videos/ANIMES/Overlord', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*subete.*ga.*f.*ni.*naru.*$', '/mnt/share/Videos/ANIMES/Subete ga F ni Naru', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*akagami.*no.*shirayukihime.*$', '/mnt/share/Videos/ANIMES/Akagami no Shirayukihime', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*ore.*monogatari.*$', '/mnt/share/Videos/ANIMES/Ore Monogatari!!', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*hellsing.*ultimate.*$', '/mnt/share/Videos/ANIMES/Hellsing Ultimate', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*amaama.*to.*inazuma.*$', '/mnt/share/Videos/ANIMES/Amaama to Inazuma', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*rekan.*$', '/mnt/share/Videos/ANIMES/Re-Kan!', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*parasyte.*.*the.*maxim.*$', '/mnt/share/Videos/ANIMES/Parasyte - the maxim', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*etotama.*$', '/mnt/share/Videos/ANIMES/Etotama', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*psycho.*pass.*2.*$', '/mnt/share/Videos/ANIMES/Psycho Pass 2', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*mayoiga.*$', '/mnt/share/Videos/ANIMES/Mayoiga', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*one.*piece.*$', '/mnt/share/Videos/ANIMES/One Piece', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*btooom.*$', '/mnt/share/Videos/ANIMES/Btooom', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*mikagura.*gakuen.*kumikyoku.*$', '/mnt/share/Videos/ANIMES/Mikagura Gakuen Kumikyoku', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*musaigen.*no.*phantom.*world.*$', '/mnt/share/Videos/ANIMES/Musaigen no Phantom World', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*kekkai.*sensen.*$', '/mnt/share/Videos/ANIMES/Kekkai Sensen', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*luck.*logic.*$', '/mnt/share/Videos/ANIMES/Luck & Logic', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*shingeki.*no.*bahamut.*$', '/mnt/share/Videos/ANIMES/Shingeki no Bahamut', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*horriblesubs.*nagi.*no.*asakura.*$', '/mnt/share/Videos/ANIMES/Nagi no Asukara', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*akuma.*no.*riddle.*$', '/mnt/share/Videos/ANIMES/Akuma no Riddle', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*hai.*to.*gensou.*no.*gimgar.*$', '/mnt/share/Videos/ANIMES/Hai to Gensou no Grimgar', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*wolf.*rain.*$', '/mnt/share/Videos/ANIMES/Wolf''s Rain', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*bungou.*stray.*dogs.*$', '/mnt/share/Videos/ANIMES/Bungou Stray Dogs', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*mekakucity.*actors.*$', '/mnt/share/Videos/ANIMES/Mekakucity Actors', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*terra.*formars.*$', '/mnt/share/Videos/ANIMES/Terra Formars', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*uta.*no.*prince.*sama.*revolutions.*$', '/mnt/share/Videos/ANIMES/Uta no Prince Sama Revolutions', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*she.*and.*her.*cat.*everything.*flows.*$', '/mnt/share/Videos/ANIMES/She and Her Cat - Everything Flows', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*plastic.*memories.*$', '/mnt/share/Videos/ANIMES/Plastic Memories', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*garo.*.*the.*animation.*$', '/mnt/share/Videos/ANIMES/Garo - The Animation', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*trinity.*seven.*$', '/mnt/share/Videos/ANIMES/Trinity Seven', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*seraph.*of.*the.*end.*s2.*$', '/mnt/share/Videos/ANIMES/Seraph of the End S2', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*fairy.*tail.*s2.*$', '/mnt/share/Videos/ANIMES/Fairy Tail S2', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*knights.*of.*sidonia.*$', '/mnt/share/Videos/ANIMES/Knights of Sidonia', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*another.*$', '/mnt/share/Videos/ANIMES/Another', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*hibike.*euphonium.*$', '/mnt/share/Videos/ANIMES/Hibike! Euphonium', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*ao.*no.*kanata.*no.*four.*rhythm.*$', '/mnt/share/Videos/ANIMES/Ao no Kanata no Four Rhythm', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*rolling.*girls.*$', '/mnt/share/Videos/ANIMES/Rolling Girls', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*heavy.*object.*$', '/mnt/share/Videos/ANIMES/Heavy Object', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*shigatsu.*wa.*kimi.*no.*uso.*$', '/mnt/share/Videos/ANIMES/Shigatsu wa Kimi no Uso', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*blade.*and.*soul.*$', '/mnt/share/Videos/ANIMES/Blade and Soul', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*dagashi.*kashi.*$', '/mnt/share/Videos/ANIMES/Dagashi Kashi', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*brynhildr.*in.*the.*darkness.*$', '/mnt/share/Videos/ANIMES/Brynhildr in the Darkness', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*robotics.*notes.*$', '/mnt/share/Videos/ANIMES/Robotics;Notes', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*re.*life.*$', '/mnt/share/Videos/ANIMES/ReLIFE', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*death.*parade.*$', '/mnt/share/Videos/ANIMES/Death Parade', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*yahari.*ore.*no.*seishun.*love.*come.*wa.*machigatteiru.*zoku.*$', '/mnt/share/Videos/ANIMES/Yahari Ore no Seishun Love Come wa Machigatteiru Zoku', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*kuromukuro.*$', '/mnt/share/Videos/ANIMES/Kuromukuro', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*seraph.*of.*the.*end.*$', '/mnt/share/Videos/ANIMES/Seraph of the End', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*gintama.*s3.*$', '/mnt/share/Videos/ANIMES/Gintama S3', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*bokura.*wa.*minna.*kawaisou.*$', '/mnt/share/Videos/ANIMES/Bokura wa Minna Kawaisou', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*urawa.*no.*usagi.*chan.*$', '/mnt/share/Videos/ANIMES/Urawa no Usagi-chan', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*show.*by.*rock.*$', '/mnt/share/Videos/ANIMES/Show By Rock!!', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*taboo.*tatoo.*$', '/mnt/share/Videos/ANIMES/Taboo Tatoo', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*rokka.*no.*yuusha.*$', '/mnt/share/Videos/ANIMES/Rokka no Yuusha', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*tokyo.*ghoul.*$', '/mnt/share/Videos/ANIMES/Tokyo Ghoul', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*soul.*eater.*not.*$', '/mnt/share/Videos/ANIMES/Soul Eater Not!', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*zankyou.*no.*terror.*$', '/mnt/share/Videos/ANIMES/Zankyou no Terror', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*ghost.*in.*the.*shell.*arise.*.*alternative.*architecture.*$', '/mnt/share/Videos/ANIMES/Ghost in the Shell Arise - Alternative Architecture', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*concrete.*revolution.*$', '/mnt/share/Videos/ANIMES/Concrete Revolutio', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*dramatical.*murder.*$', '/mnt/share/Videos/ANIMES/DRAMAtical Murder', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*punch.*line.*$', '/mnt/share/Videos/ANIMES/Punch Line', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*god.*eater.*$', '/mnt/share/Videos/ANIMES/GOD EATER', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*barakamon.*$', '/mnt/share/Videos/ANIMES/Barakamon', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*danna.*ga.*nani.*wo.*itteiru.*ka.*wakaranai.*ken.*s2.*$', '/mnt/share/Videos/ANIMES/Danna ga Nani wo Itteiru ka Wakaranai Ken S2', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*ushio.*to.*tora.*$', '/mnt/share/Videos/ANIMES/Ushio to Tora', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*akame.*ga.*kill.*$', '/mnt/share/Videos/ANIMES/Akame Ga Kill!', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*akawa.*under.*the.*bridge.*$', '/mnt/share/Videos/ANIMES/Arakawa Under the Bridge', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*psycho.*pass.*extended.*edition.*$', '/mnt/share/Videos/ANIMES/PSYCHO-PASS Extended Edition', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*beelzebub.*$', '/mnt/share/Videos/ANIMES/Beelzebub', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*houkago.*no.*pleiades.*$', '/mnt/share/Videos/ANIMES/Houkago no Pleiades', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*tokyo.*esp.*$', '/mnt/share/Videos/ANIMES/Tokyo ESP', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*new.*game.*$', '/mnt/share/Videos/ANIMES/New Game!', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*saijaku.*muhai.*no.*bahamut.*$', '/mnt/share/Videos/ANIMES/Saijaku Muhai no Bahamut', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*black.*bullet.*$', '/mnt/share/Videos/ANIMES/Black Bullet', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*gangsta.*$', '/mnt/share/Videos/ANIMES/Gangsta', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*flying.*witch.*$', '/mnt/share/Videos/ANIMES/Flying Witch', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*re.*zero.*kara.*hajimeru.*isekai.*seikatsu.*$', '/mnt/share/Videos/ANIMES/Re Zero kara Hajimeru Isekai Seikatsu', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*hunter.*x.*hunter.*$', '/mnt/share/Videos/ANIMES/Hunter X Hunter', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*assassination.*classroom.*$', '/mnt/share/Videos/ANIMES/Assassination Classroom', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*kuma.*miko.*$', '/mnt/share/Videos/ANIMES/Kuma Miko', 2);
INSERT INTO rules (regex, destination, repo) VALUES ('^.*planetarian.*$', '/mnt/share/Videos/ANIMES/Planetarian', 2);
